"""add pipeline tables

Revision ID: 03f1b72c8cb6
Revises: c56163e9fc95
Create Date: 2026-07-18 15:00:11.164113
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03f1b72c8cb6'
down_revision: str | None = 'c56163e9fc95'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_profile_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_import_run_id', sa.UUID(), nullable=True),
    sa.Column('total_videos', sa.Integer(), nullable=True),
    sa.Column('total_views', sa.BigInteger(), nullable=True),
    sa.Column('total_subscribers', sa.BigInteger(), nullable=True),
    sa.Column('avg_views_per_video', sa.Float(), nullable=True),
    sa.Column('avg_view_duration_seconds', sa.Float(), nullable=True),
    sa.Column('total_watch_time_hours', sa.Float(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_profile_id'], ['creator_profiles.id'], name=op.f('fk_metric_snapshots_creator_profile_id_creator_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_import_run_id'], ['import_runs.id'], name=op.f('fk_metric_snapshots_source_import_run_id_import_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_snapshots'))
    )
    op.create_index(op.f('ix_metric_snapshots_creator_profile_id'), 'metric_snapshots', ['creator_profile_id'], unique=False)
    op.create_index('ix_metric_snapshots_creator_snapshot', 'metric_snapshots', ['creator_profile_id', 'snapshot_at'], unique=True)
    op.create_index(op.f('ix_metric_snapshots_snapshot_at'), 'metric_snapshots', ['snapshot_at'], unique=False)
    op.create_table('metric_feature_vectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_profile_id', sa.UUID(), nullable=False),
    sa.Column('source_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_schema_version', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_profile_id'], ['creator_profiles.id'], name=op.f('fk_metric_feature_vectors_creator_profile_id_creator_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_snapshot_id'], ['metric_snapshots.id'], name=op.f('fk_metric_feature_vectors_source_snapshot_id_metric_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_feature_vectors'))
    )
    op.create_index(op.f('ix_metric_feature_vectors_creator_profile_id'), 'metric_feature_vectors', ['creator_profile_id'], unique=False)
    op.create_index('ix_metric_feature_vectors_creator_snapshot', 'metric_feature_vectors', ['creator_profile_id', 'source_snapshot_id'], unique=False)
    op.create_index(op.f('ix_metric_feature_vectors_source_snapshot_id'), 'metric_feature_vectors', ['source_snapshot_id'], unique=True)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_profile_id', sa.UUID(), nullable=False),
    sa.Column('source_feature_vector_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_profile_id'], ['creator_profiles.id'], name=op.f('fk_findings_creator_profile_id_creator_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_feature_vector_id'], ['metric_feature_vectors.id'], name=op.f('fk_findings_source_feature_vector_id_metric_feature_vectors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    op.create_index(op.f('ix_findings_creator_profile_id'), 'findings', ['creator_profile_id'], unique=False)
    op.create_index('ix_findings_creator_rule', 'findings', ['creator_profile_id', 'rule_id'], unique=False)
    op.create_index('ix_findings_feature_vector', 'findings', ['source_feature_vector_id'], unique=False)
    op.create_index(op.f('ix_findings_rule_id'), 'findings', ['rule_id'], unique=False)
    op.create_index(op.f('ix_findings_source_feature_vector_id'), 'findings', ['source_feature_vector_id'], unique=False)
    op.create_table('pipeline_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_profile_id', sa.UUID(), nullable=False),
    sa.Column('source_finding_id', sa.UUID(), nullable=False),
    sa.Column('source_feature_vector_id', sa.UUID(), nullable=False),
    sa.Column('source_rule_id', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('supporting_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_profile_id'], ['creator_profiles.id'], name=op.f('fk_pipeline_evidence_creator_profile_id_creator_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_feature_vector_id'], ['metric_feature_vectors.id'], name=op.f('fk_pipeline_evidence_source_feature_vector_id_metric_feature_vectors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_finding_id'], ['findings.id'], name=op.f('fk_pipeline_evidence_source_finding_id_findings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_evidence'))
    )
    op.create_index('ix_pipeline_evidence_creator_finding', 'pipeline_evidence', ['creator_profile_id', 'source_finding_id'], unique=False)
    op.create_index(op.f('ix_pipeline_evidence_creator_profile_id'), 'pipeline_evidence', ['creator_profile_id'], unique=False)
    op.create_index(op.f('ix_pipeline_evidence_source_feature_vector_id'), 'pipeline_evidence', ['source_feature_vector_id'], unique=False)
    op.create_index(op.f('ix_pipeline_evidence_source_finding_id'), 'pipeline_evidence', ['source_finding_id'], unique=True)
    op.create_table('pipeline_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_profile_id', sa.UUID(), nullable=False),
    sa.Column('source_evidence_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('supporting_evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_profile_id'], ['creator_profiles.id'], name=op.f('fk_pipeline_claims_creator_profile_id_creator_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['pipeline_evidence.id'], name=op.f('fk_pipeline_claims_source_evidence_id_pipeline_evidence'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_claims'))
    )
    op.create_index('ix_pipeline_claims_creator_evidence', 'pipeline_claims', ['creator_profile_id', 'source_evidence_id'], unique=False)
    op.create_index(op.f('ix_pipeline_claims_creator_profile_id'), 'pipeline_claims', ['creator_profile_id'], unique=False)
    op.create_index(op.f('ix_pipeline_claims_source_evidence_id'), 'pipeline_claims', ['source_evidence_id'], unique=True)
    op.create_table('pipeline_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_profile_id', sa.UUID(), nullable=False),
    sa.Column('source_claim_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_outcome', sa.String(length=512), nullable=True),
    sa.Column('success_metric', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_profile_id'], ['creator_profiles.id'], name=op.f('fk_pipeline_recommendations_creator_profile_id_creator_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_claim_id'], ['pipeline_claims.id'], name=op.f('fk_pipeline_recommendations_source_claim_id_pipeline_claims'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_recommendations'))
    )
    op.create_index('ix_pipeline_recommendations_creator_claim', 'pipeline_recommendations', ['creator_profile_id', 'source_claim_id'], unique=False)
    op.create_index(op.f('ix_pipeline_recommendations_creator_profile_id'), 'pipeline_recommendations', ['creator_profile_id'], unique=False)
    op.create_index(op.f('ix_pipeline_recommendations_source_claim_id'), 'pipeline_recommendations', ['source_claim_id'], unique=True)
    op.create_table('pipeline_experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creator_profile_id', sa.UUID(), nullable=False),
    sa.Column('source_recommendation_id', sa.UUID(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('success_metric', sa.String(length=256), nullable=True),
    sa.Column('expected_outcome', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_profile_id'], ['creator_profiles.id'], name=op.f('fk_pipeline_experiments_creator_profile_id_creator_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_recommendation_id'], ['pipeline_recommendations.id'], name=op.f('fk_pipeline_experiments_source_recommendation_id_pipeline_recommendations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_experiments'))
    )
    op.create_index(op.f('ix_pipeline_experiments_creator_profile_id'), 'pipeline_experiments', ['creator_profile_id'], unique=False)
    op.create_index('ix_pipeline_experiments_creator_rec', 'pipeline_experiments', ['creator_profile_id', 'source_recommendation_id'], unique=False)
    op.create_index(op.f('ix_pipeline_experiments_source_recommendation_id'), 'pipeline_experiments', ['source_recommendation_id'], unique=True)
    op.create_index(op.f('ix_pipeline_experiments_status'), 'pipeline_experiments', ['status'], unique=False)
    # Only pipeline table creation — all unrelated diff is intentionally skipped
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_experiments_status'), table_name='pipeline_experiments')
    op.drop_index(op.f('ix_pipeline_experiments_source_recommendation_id'), table_name='pipeline_experiments')
    op.drop_index('ix_pipeline_experiments_creator_rec', table_name='pipeline_experiments')
    op.drop_index(op.f('ix_pipeline_experiments_creator_profile_id'), table_name='pipeline_experiments')
    op.drop_table('pipeline_experiments')
    op.drop_index(op.f('ix_pipeline_recommendations_source_claim_id'), table_name='pipeline_recommendations')
    op.drop_index(op.f('ix_pipeline_recommendations_creator_profile_id'), table_name='pipeline_recommendations')
    op.drop_index('ix_pipeline_recommendations_creator_claim', table_name='pipeline_recommendations')
    op.drop_table('pipeline_recommendations')
    op.drop_index(op.f('ix_pipeline_claims_source_evidence_id'), table_name='pipeline_claims')
    op.drop_index(op.f('ix_pipeline_claims_creator_profile_id'), table_name='pipeline_claims')
    op.drop_index('ix_pipeline_claims_creator_evidence', table_name='pipeline_claims')
    op.drop_table('pipeline_claims')
    op.drop_index(op.f('ix_pipeline_evidence_source_finding_id'), table_name='pipeline_evidence')
    op.drop_index(op.f('ix_pipeline_evidence_source_feature_vector_id'), table_name='pipeline_evidence')
    op.drop_index(op.f('ix_pipeline_evidence_creator_profile_id'), table_name='pipeline_evidence')
    op.drop_index('ix_pipeline_evidence_creator_finding', table_name='pipeline_evidence')
    op.drop_table('pipeline_evidence')
    op.drop_index(op.f('ix_findings_source_feature_vector_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_rule_id'), table_name='findings')
    op.drop_index('ix_findings_feature_vector', table_name='findings')
    op.drop_index('ix_findings_creator_rule', table_name='findings')
    op.drop_index(op.f('ix_findings_creator_profile_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_metric_feature_vectors_source_snapshot_id'), table_name='metric_feature_vectors')
    op.drop_index('ix_metric_feature_vectors_creator_snapshot', table_name='metric_feature_vectors')
    op.drop_index(op.f('ix_metric_feature_vectors_creator_profile_id'), table_name='metric_feature_vectors')
    op.drop_table('metric_feature_vectors')
    op.drop_index(op.f('ix_metric_snapshots_snapshot_at'), table_name='metric_snapshots')
    op.drop_index('ix_metric_snapshots_creator_snapshot', table_name='metric_snapshots')
    op.drop_index(op.f('ix_metric_snapshots_creator_profile_id'), table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    # ### end Alembic commands ###
